version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  seeder:
    build: ./script
    depends_on:
      - mongodb

  app:
    build: ./app
    ports:
      - 8763:8763
    depends_on:
      - mongodb
