version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8763:8763
    depends_on:
      - mongodb
  seeder:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    depends_on:
      - mongodb
